apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calander
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: calendar-21996d74-e163-42ed-88aa-fa19370c7eb4
      eventName: calendar-21996d74-e163-42ed-88aa-fa19370c7eb4
      eventSourceName: calander-nw
  triggers:
    - template:
        name: status-check
        conditions: calendar-21996d74-e163-42ed-88aa-fa19370c7eb4
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: calander-status-check-
              spec:
                workflowTemplateRef:
                  name: check-status
          parameters: []
