apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: push-commit
spec:
  eventBusName: codefresh-eventbus
  github:
    push-commit:
      active: true
      apiToken:
        key: git_token
        name: autopilot-secret
      contentType: json
      deleteHookOnFinish: true
      events:
      - push
      githubBaseURL: https://api.github.com/
      insecure: true
      repositories:
      - names:
        - test-skip-validation_git-source
        owner: kim-codefresh
      webhook:
        endpoint: /webhooks/test-skip-validation/push-commit/push-commit
        method: POST
        port: "80"
        url: https://kim-dev.pipeline-team.cf-cd.com
  service:
    ports:
    - port: 80
  template:
    container:
      name: ""
      resources: {}
